#! /bin/sh
# integrit - file integrity verification system
# Copyright (C) 2006 Ed L. Cashin
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 

set -ex
me=make-config
ignorecfg=0

while getopts i opt
do
    case "$opt" in
      '?') echo "$0 [-i] testdir"; exit 1;;
        i) ignorecfg=1;;
    esac
    OPTIND=1
    shift
done

testdir=$1
if [ -z "$testdir" ]; then
  echo "$me: missing test directory" 1>&2
  exit 1
fi

cat <<EOF > $testdir/test.conf
root = $testdir
! $testdir/one
known = $testdir/known.cdb
current = $testdir/curr.cdb

EOF

if [ $ignorecfg = 1 ]; then
cat <<EOF >> $testdir/test.conf
!$testdir/known.cdb
!$testdir/curr.cdb
!$testdir/test.out
EOF
fi
