#! /bin/sh
# integrit - file integrity verification system
# Copyright (C) 2006 Ed L. Cashin
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 

# this script is for the developer rebuilding dep.mak before
# a release.
# 

debug=no
debug() {
    if [ "$debug" = "yes" ]; then
	echo $*
    fi
}

IFS=""
while read line; do
    # skip command lines
    if [ ! -z "`echo $line | grep '^[	]'`" ]; then
	echo $line
	continue
    fi
    target=`echo $line | sed 's/:.*//'`
    # remove "gnupg/" from object files 
    target=`echo $target | sed 's/gnupg\///'`
    deps=`echo $line | sed 's/^[^:][^:]*: *//'`
    trdeps=
    IFS=" 	"
    for f in $deps; do 
	# add $(srcdir) to sources
	trdeps="$trdeps \$(srcdir)/$f"
    done
    IFS=""
    echo $target: $trdeps
done

