# generated by Makefile
ls.o : ${srcdir}/ls.c  Makefile
	${CC} ${CPPFLAGS} ${CFLAGS} ${DEFS} -o $@ -c  ${srcdir}/ls.c
viewdb.o : ${srcdir}/viewdb.c  Makefile
	${CC} ${CPPFLAGS} ${CFLAGS} ${DEFS} -o $@ -c  ${srcdir}/viewdb.c
